# This is a basic workflow to help you get started with Actions

name: Status Check

# Controls when the action will run.
on:
  # Run when any design files are changed
  push:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'
      - '**.kicad_pro'
      - '.github/**.yml'
  pull_request:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'
      - '**.kicad_pro'
      - '.github/**.yml'
  merge_group:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
#jobs:
  erc:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kicad/kicad:8.0
      options: --user root
    steps:
      - uses: actions/checkout@v4
      
      - run: cp -r /home/kicad/.config/kicad/ ~/.config/kicad/
      - run: kicad-cli sch erc --exit-code-violations GeoMCU.kicad_sch
      
      - name: Artifacts Upload
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ERC Report
          path: GeoMCU.rpt

  drc:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kicad/kicad:8.0
      options: --user root
    steps:
      - uses: actions/checkout@v4
      
      - run: cp -r /home/kicad/.config/kicad/ ~/.config/kicad/
      - run: kicad-cli pcb drc --exit-code-violations GeoMCU.kicad_pcb
      
      - name: Artifacts Upload
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: DRC Report
          path: GeoMCU.rpt
  docs:
    needs: [erc, drc]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kicad/kicad:8.0
      options: --user root
    steps:
      - uses: actions/checkout@v4

      - run: cp -r /home/kicad/.config/kicad/ ~/.config/kicad/
      - run: |
          kicad-cli sch export pdf GeoMCU.kicad_sch -o docs/GeoMCU-schematic.pdf
          kicad-cli pcb export pdf --include-border-title GeoMCU.kicad_pcb -o docs/GeoMCU-F_Cu.pdf --layers="F.Cu,User.Drawings,User.Comments,Edge.Cuts"
          kicad-cli pcb export pdf --include-border-title GeoMCU.kicad_pcb -o docs/GeoMCU-In1_Cu.pdf --layers="In1.Cu,User.Drawings,User.Comments,Edge.Cuts"
          kicad-cli pcb export pdf --include-border-title GeoMCU.kicad_pcb -o docs/GeoMCU-In2_Cu.pdf --layers="In2.Cu,User.Drawings,User.Comments,Edge.Cuts"
          kicad-cli pcb export pdf --include-border-title GeoMCU.kicad_pcb -o docs/GeoMCU-B_Cu.pdf --layers="B.Cu,User.Drawings,User.Comments,Edge.Cuts" --mirror
      
      
      - name: Google Chat Notification
        uses: SimonScholz/google-chat-action@main
        if: always()
        with:
          title: PDF Exports
          webhookUrl: ${{ secrets.PIGHARDWARE_GCHAT_WEBHOOK_URL }}
          jobStatus: ${{ job.status }}

      - name: Artifacts Upload
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Viewable Docs
          path: docs
