# This is a basic workflow to help you get started with Actions

name: Viewable Docs Export

# Controls when the action will run.
on:
  # Run when any design files are changed
  push:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'
      - '**.kicad_pro'
  pull_request:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'
      - '**.kicad_pro'
  merge_group:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'
      - '**.kicad_pro'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
#jobs:
  exports:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad8_auto:latest
    steps:
      - uses: actions/checkout@v4
      - name: KiBot Docs Export
        uses: INTI-CMNB/KiBot@v2_k7
        with:
          # Required - kibot config file
          config: .github/docs.kibot.yaml
          # optional - prefix to output defined in config
          dir: docs
          # optional - verbose output info
          verbose: 1
      
      
      - name: Google Chat Notification
        uses: SimonScholz/google-chat-action@main
        if: always()
        with:
          title: PDF Exports
          webhookUrl: ${{ secrets.PIGHARDWARE_GCHAT_WEBHOOK_URL }}
          jobStatus: ${{ job.status }}

      - name: Artifacts Upload
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: docs
          path: docs
