# This is a basic workflow to help you get started with Actions

name: Checks and Documentation

# Controls when the action will run.
on:
  # Run when any design files are changed
  push:
    paths:
      - "**.kicad_sch"
      - "**.kicad_pcb"
      - "**.kicad_pro"
      - ".github/**.yml"
  pull_request:
    paths:
      - "**.kicad_sch"
      - "**.kicad_pcb"
      - "**.kicad_pro"
      - ".github/**.yml"
  merge_group:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  erc:
    name: "Electrical Rules Check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-for-kicad/kicad-actions@v1.6-k9.0
        with:
          run_erc: true
          schematic_file_name: GeoMCU.kicad_sch
          erc_output_file_name: erc.rpt

      - name: Artifacts Upload
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ERC Report
          path: erc.rpt

  drc:
    name: "Design Rules Check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-for-kicad/kicad-actions@v1.6-k9.0
        with:
          run_drc: true
          schematic_file_name: GeoMCU.kicad_sch
          pcb_file_name: GeoMCU.kicad_pcb     
          drc_output_file_name: drc.rpt

      - name: Artifacts Upload
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: DRC Report
          path: drc.rpt

  docs:
    name: "PDF Exports"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: mkdir -p docs/

      - uses: actions-for-kicad/kicad-actions@v1.6-k9.0
        with:
          entrypoint: kicad-cli
          args: jobset run -f docs.kicad_jobset GeoMCU.kicad_pro
            
      - name: Artifacts Upload
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Viewable Docs
          path: docs
