# This is a basic workflow to help you get started with Actions

name: Design Rules Check

# Controls when the action will run.
on:
  # Run when any design files are changed
  push:
    paths:
      - '**.kicad_sch'
  pull_request:
    paths:
      - '**.kicad_sch'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
#jobs:
  exports:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad8_auto_full:latest
    steps:
      - uses: actions/checkout@v4
      
      - run: kicad-cli sch erc --exit-code-violations GeoMCU.kicad_sch
      
      - name: Artifacts Upload
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Report
          path: GeoMCU.rpt
