# This is a basic workflow to help you get started with Actions

name: KiCad Exports

# Controls when the action will run.
on:
  # Run when any design files are changed
  push:
    paths:
      - '**.sch'
      - '**.kicad_pcb'
      - '**.pro'
  pull_request:
    paths:
      - '**.sch'
      - '**.kicad_pcb'
      - '**.pro'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
#jobs:
  exports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nerdyscout/kicad-exports@v2.3
        with:
          # Required - kibot config file
          config: docs.kibot.yaml
          # optional - prefix to output defined in config
          dir: docs
          # optional - schematic file
          schema: 'GeoMCU.sch'
          # optional - PCB design file
          board: 'GeoMCU.kicad_pcb'
          # optional - verbose output info
          verbose: 2
      
      
      - name: Google Chat Notification
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: Exports
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}
          if: always()

      - uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs
          if: always()
