# This is a basic workflow to help you get started with Actions

name: JLCPCB Exports

# Controls when the action will run.
on:
  # Run when any design files are changed
  push:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'
      - '**.kicad_pro'
  pull_request:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'
      - '**.kicad_pro'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
#jobs:
  exports:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad8_auto:latest
    steps:
      - uses: actions/checkout@v4
      
      - run: |
          kikit fab jlcpcb GeoMCU.kicad_pcb --assembly --field LCSC --schematic GeoMCU.kicad_sch docs/
          rm docs/gerbers.zip
      
      - name: Google Chat Notification
        uses: SimonScholz/google-chat-action@main
        if: always()
        with:
          title: JLCPCB Fab Exports
          webhookUrl: ${{ secrets.PIGHARDWARE_GCHAT_WEBHOOK_URL }}
          jobStatus: ${{ job.status }}

      - name: Artifacts Upload
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: fab_JLCPCB
          path: docs
